"""
Utility Functions for BLE Communication and Machine Learning Evaluation

This module centralizes helper functions required to discover, filter, and configure
the Nordic Thingy:52 hardware endpoints, as well as tools to plot and save
performance evaluation metrics from machine learning models.
"""

import struct
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from matplotlib.ticker import PercentFormatter
from sklearn.metrics import confusion_matrix
from bleak import BleakScanner
from bleak.backends.device import BLEDevice

# Import the mapped hardware addresses from your constants file
from utils.constants import UIS_LED_UUID



# async function: a function that takes time --> the program can continue to run while waiting for the function to complete
# await can be used only inside async functions. Blocks the function but not the program. The program can continue to run while waiting for the function to complete
async def scan():

    """
    Scan for available Bluetooth Low Energy (BLE) devices in the environment.

    Returns:
        list[BLEDevice]: A list of discovered BLE devices.
    """

    # use_bdaddr=True ensures stable hardware address handling on macOS systems
    devices = await BleakScanner.discover(cb=dict(use_bdaddr=True))
    return devices



def find(discovered_devices: list[BLEDevice], addresses: list[str]) -> list[BLEDevice]:
    
    """
    Filter the discovered BLE devices to match specific target hardware addresses.

    Args:
        discovered_devices (list[BLEDevice]): Raw list of scanned devices from the environment.
        addresses (list[str]): Target MAC/hardware addresses to search for.

    Returns:
        list[BLEDevice]: A list of matched BLE devices.
    """

    my_devices = []
    for i in range(len(discovered_devices)):
        if discovered_devices[i].address in addresses:
            my_devices.append(discovered_devices[i])
            # Optimization: Stop loop early once all target addresses are resolved
            if len(my_devices) == len(addresses):
                break
    return my_devices



async def change_status(client, status: str) -> None:

    """
    Change the LED color on the Thingy:52 to visually represent the system state.

    Args:
        client (BleakClient): The active BLE client connection.
        status (str): The operational state ("connected" for green, "recording" for red).
    """

    payload = None
    format_str = "<4B"  # 4 Unsigned Bytes: [Light Mode, Red, Green, Blue]
    constant_light = 1

    if status == "connected":
        green = (0, 255, 0)
        payload = struct.pack(format_str, constant_light, *green)

    if status == "recording":
        red = (255, 0, 0)
        payload = struct.pack(format_str, constant_light, *red)

    if payload is not None:
        # Write the packed color byte packet to the designated LED characteristic
        await client.write_gatt_char(UIS_LED_UUID, payload)



def motion_characteristics(
    step_counter_interval: int = 100,
    temperature_comp_interval: int = 100,
    magnetometer_comp_interval: int = 100,
    motion_processing_unit_freq: int = 60,
    wake_on_motion: int = 1
) -> bytes:
    
    """
    Pack the structural configuration parameters for the Thingy's internal motion sensor.

    The format string '<4H B' specifies:
        <  : Little-endian byte order.
        4H : Four 16-bit unsigned integers.
        B  : One 8-bit unsigned integer.

    Returns:
        bytes: Packed byte array ready to be transmitted to TMS_CONF_UUID.
    """

    format_str = "<4H B"
    return struct.pack(
        format_str,
        step_counter_interval,
        temperature_comp_interval,
        magnetometer_comp_interval,
        motion_processing_unit_freq,
        wake_on_motion
    )



# Confusion Matrix Analysis Function
def cm_analysis(
    y_true: np.ndarray, 
    y_pred: np.ndarray, 
    filename: str, 
    labels: list, 
    classes: list, 
    ymap: dict = None, 
    fig_size: tuple = (17, 14), 
    specific_title: str = None
) -> None:
    
    """
    Generate, plot, and save a highly detailed Confusion Matrix heatmap with annotations.
    Saves both a visual plot chart (.png) and the normalized data (.csv) to disk.

    Args:
        y_true (array-like): Ground truth target classification labels.
        y_pred (array-like): Predicted targets generated by the machine learning model.
        filename (str): Base destination file path (without extensions) to store artifacts.
        labels (list): Sorting order index of class labels inside the confusion matrix.
        classes (list): Descriptive class names to display on the chart axes.
        ymap (dict, optional): Mapping dictionary to translate raw labels into readable strings.
        fig_size (tuple): Dimensions of the generated output figure plot.
        specific_title (str, optional): Custom title text string for the visual graph.
    """

    sns.set(font_scale=2)

    if ymap is not None:
        y_pred = [ymap[yi] for yi in y_pred]
        y_true = [ymap[yi] for yi in y_true]
        labels = [ymap[yi] for yi in labels]
        
    cm = confusion_matrix(y_true, y_pred, labels=labels)
    cm_sum = np.sum(cm, axis=1, keepdims=True)
    cm_perc = cm / cm_sum.astype(float) * 100
    annot = np.empty_like(cm).astype(str)
    nrows, ncols = cm.shape
    
    for i in range(nrows):
        for j in range(ncols):
            c = cm[i, j]
            p = cm_perc[i, j]
            if i == j:
                s = cm_sum[i][0]
                annot[i, j] = '%.2f%%\n%d/%d' % (p, c, s)
            else:
                annot[i, j] = '%.2f%%\n%d' % (p, c)
                
    cm = confusion_matrix(y_true, y_pred, labels=labels, normalize='true')
    cm = pd.DataFrame(cm, index=labels, columns=labels)
    cm = cm * 100
    cm.index.name = 'True Label'
    cm.columns.name = 'Predicted Label'
    
    fig, ax = plt.subplots(figsize=fig_size)
    plt.yticks(va='center')

    sns.heatmap(
        cm, annot=annot, fmt='', ax=ax, 
        xticklabels=classes, yticklabels=classes, 
        cbar=True, cbar_kws={'format': PercentFormatter()}, 
        cmap="Blues"
    )

    if specific_title is not None:
        plt.title(specific_title, fontsize=40, fontweight="bold")

    plt.subplots_adjust(hspace=0.5, top=2.88)
    plt.tight_layout()

    plt.savefig(f"{filename}.png", bbox_inches='tight', dpi=300)
    cm.to_csv(f"{filename}.csv")
    plt.close()



def get_uuid(device: BLEDevice) -> str:

    """
    Extract the hardware identifier or MAC address string from a BLE device object.
    Specifically structured to bypass address parsing edge cases unique to macOS.

    Args:
        device (BLEDevice): Discovered BLE device target.

    Returns:
        str: Extracted identifier string value.
    """
    
    return str(device.details[0].identifier).split(",")[1].split("= ")[1]



